### ISSUE TITLE
Feature request: Add episode title to widgets

### ISSUE THREAD

**Issue by IG2022** [heppenowski/skin.cosmic#82]
Hi heppen, thanks so much for the great skin this has been my go to for some time now

I just wanted to find out if it would be possible to add episode titles to widgets. I have some lists that have episodes but I am unable to get see the episode title in the widgets. I noticed that with movies and tv shows there is a "tagline" above the synopsis, would it be possible to add the episode title above the episode synopsis in the same the way there is a "tagline" for movies and tv show widgets?

Thanks!

**Comment by nfm886** [comment]
Hi,
Thanks for you request. I'm currently kind of busy. I'm working on new skin based on Cosmic and don't have much time to work on Cosmic. I'm planning to backport some fixes and functionalities from new skin to Cosmic but it may happen around new year when Primus will be finished. 
Want to focus only on it to publish a "beta preview" as fast as possible.

**Comment by IG2022** [comment]
> Hi, Thanks for you request. I'm currently kind of busy. I'm working on new skin based on Cosmic and don't have much time to work on Cosmic. I'm planning to backport some fixes and functionalities from new skin to Cosmic but it may happen around new year when Primus will be finished. Want to focus only on it to publish a "beta preview" as fast as possible.

Hey thanks so much for your reply, I really appreciate it.  Not a problem at all! It's great to hear that you are working on a new skin based on cosmic, I'm looking forward to seeing that when it comes out! If you need any beta testers feel free to reach out to me!

**Comment by nfm886** [comment]
Short teaser for people who following my GitHub and will see this feature request: https://streamable.com/8eg6x8 ;)
It will be kind of different approach to how widgets are handled. One local widget with banners for each menu entries and global widget wall. For now, we have home screen but I'm planning to add many more view types, simplify settings from Cosmic, so customization won't be needed to enjoy this skin and some stuff more which we will see in next few weeks :)

**Comment by IG2022** [comment]
> Short teaser for people who following my GitHub and will see this feature request: https://streamable.com/8eg6x8 ;) It will be kind of different approach to how widgets are handled. One local widget with banners for each menu entries and global widget wall. For now, we have home screen but I'm planning to add many more view types, simplify settings from Cosmic, so customization won't be needed to enjoy this skin and some stuff more which we will see in next few weeks :)

This looks incredible, definitely alot different compared to any other skin that I've see our there in regard to widgets. I'm honored to have seen this teaser first! :D looking forward to seeing what else you do with the new skin.

**Comment by nfm886** [comment]
Thank you :)

> I'm honored to have seen this teaser first! :D

I'm uploading clips from time to time with current progress on Addons4Kodi's discord: https://discord.gg/SqX7buB ;)

> Will you make announcements about the new skin here?

I will post a topic on forum.kodi.tv for sure :)

**Comment by IG2022** [comment]
> Thank you :)
> 
> > I'm honored to have seen this teaser first! :D
> 
> I'm uploading clips from time to time with current progress on Addons4Kodi's discord: https://discord.gg/SqX7buB ;)
> 
> > Will you make announcements about the new skin here?
> 
> I will post a topic on forum.kodi.tv for sure :)

Perfect! I'll look out for any updates non forum.kodi.tv and on the discord server... Keep up the good work!

**Comment by IG2022** [comment]
Thank you for adding episode titles in prime view widgets! I saw your update on discord and downloaded it today. Thanks for all your hard work it's looking great!
