### ISSUE TITLE
Poster Showcase View issues

### ISSUE THREAD

**Issue by meesterexx** [heppenowski/skin.cosmic#87]
I know Cosmic is a WIP and undergoing many changes, but will you be revisiting the Poster Showcase view? I've noticed some issues:
1. The selection box is the wrong size and  in the wrong position:
![screenshot00000](https://user-images.githubusercontent.com/13154733/181345763-aacff3a0-a71d-4d31-bf90-f6abcba476d0.png)

2. At the show level, the watched indicators are duplicated, they are on the posters and on the selection box:
![screenshot00001](https://user-images.githubusercontent.com/13154733/181345971-c0173647-5ab7-4439-b242-614775b1de99.png)

3.  Once you choose Poster Showcase in the view and close the option box for choosing view type, you can't get back to the option box by pressing up (like you can on Flix View) so you can't change the view type again. Left and right just scroll through the widget and wrap back around to the start or end of the widget. Pressing down does nothing.

On an unrelated note, I have Fixed/Flixed scrolling off on the home screen (Default setting), but on Flix Views it is still on. Would it be possible to have the Flix view also honor the home screen setting or add an option in the view option box to turn off Fixed/Flixed scrolling so it matches the home screen when Fixed is set to off?

I love what you're doing on the skin, the new Prime home layout looks amazing. Thank you.

**Comment by heppenowski** [comment]
Thanks for your report. Of course I will correct all the issues and sorry for them. Current state of Cosmic on Github is ekhem, ekhem ;) but it's barely usable. Probably tomorrow I will fix those issue you mentioned.

> On an unrelated note, I have Fixed/Flixed scrolling off on the home screen (Default setting), but on Flix Views it is still on. Would it be possible to have the Flix view also honor the home screen setting or add an option in the view option box to turn off Fixed/Flixed scrolling so it matches the home screen when Fixed is set to off?
I must see, don't remember current implementation of it. 

> I love what you're doing on the skin, the new Prime home layout looks amazing. Thank you.
Thanks for kind words :) I hope we will make Cosmic great again :D

**Comment by heppenowski** [comment]
This view should be fixed in most part. About this one:

> On an unrelated note, I have Fixed/Flixed scrolling off on the home screen (Default setting), but on Flix Views it is still on. Would it be possible to have the Flix view also honor the home screen setting or add an option in the view option box to turn off Fixed/Flixed scrolling so it matches the home screen when Fixed is set to off?

You are welcomed to open another issue :) Thanks for your report.

**Comment by meesterexx** [comment]
Looks great, many thanks!
