### ISSUE TITLE
Prime widget aspect ratio selection box background too large

### ISSUE THREAD

**Issue by meesterexx** [heppenowski/skin.cosmic#88]
When using the Prime aspect ratio on widgets the background of the selected item is larger than the item and not fully transparent:

Prime:
![screenshot00001](https://user-images.githubusercontent.com/13154733/209446366-b83537b6-ec66-47cc-ab4f-dceafee5110e.png)

Landscape/Fanart ratio is fine:
![screenshot00002](https://user-images.githubusercontent.com/13154733/209446381-a4ac29af-ea66-4bc9-862d-97bd4df9d472.png)

**Comment by heppenowski** [comment]
Fixed: https://github.com/heppenowski/skin.cosmic/commit/14188ddfe7f06e81e1ed4a153dfa8674e9991f8e

**Comment by meesterexx** [comment]
Thank you!

**Comment by heppenowski** [comment]
Sorry it took some time, but I'm busy currently :)
